FizzBuzz/FizzBuzz/Models/FizzBuzzModel.cs
namespace FizzBuzz.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using PagedList;
    
    public class FizzBuzzModel
    {
        [Required(ErrorMessage = "Please Enter a number")]
        [Display(Name = "Enter User Input")]
        [Range(1, 1000, ErrorMessage = "Please Enter number between 1 and 1000")]
        public int UserInput { get; set; }

        public IPagedList<string> Result { get; set; }
    }
}

FizzBuzz/FizzBuzz/Controllers/FizzBuzzController.cs
namespace FizzBuzz.Controllers
{
    using System;
    using System.Web.Mvc;
    using FizzBuzz.Service.Interface;
    using FizzBuzz.Models;
    using PagedList;

    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzRepository repository;
        private int pageSize = 20;
        private int pageNumber;

        public FizzBuzzController(IFizzBuzzRepository repository)
        {
            this.repository = repository;
        }

        [HttpGet]
        public ActionResult Home(string userInput, int? page)
        {
            if (!string.IsNullOrEmpty(userInput))
            {
                var number = Convert.ToInt32(userInput);
                var resultmodel = this.GetFizzBuzzResults(number, page);
                return View("Home", resultmodel);
            }

            return View("Home");
        }

        [HttpPost]
        public ActionResult Home(FizzBuzzModel model, int? page)
        {
            if (ModelState.IsValid)
            {
                var resultmodel = GetFizzBuzzResults(model.UserInput, page);
                return View("Home", resultmodel);
            }

            return this.View("Home");
        }

        private FizzBuzzModel GetFizzBuzzResults(int userInput, int? page)
        {
            pageNumber = page.HasValue ? Convert.ToInt32(page) : 1;
            var result = this.repository.GetResult(userInput);

            var model = new FizzBuzzModel
            {
                UserInput = userInput,
                Result = result.ToPagedList(pageNumber, pageSize)
            };

            return model;
        }
    }
}

FizzBuzz/FizzBuzz/Views/FizzBuzz/Home.cshtml
@model FizzBuzz.Models.FizzBuzzModel
@{
    ViewBag.Title = "Home";
}
@using (Html.BeginForm("Home", "FizzBuzz", FormMethod.Post))
{
   <div class="form-horizontal">
   <div class="form-group">
            @Html.LabelFor(model => model.UserInput, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.TextBoxFor(model => model.UserInput)
                @Html.ValidationMessageFor(model => model.UserInput, "", new { @class = "fizzbuzzError" })
            </div>
    </div>
   <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
  </div>
       <div>
         @if (Model != null)
            {
                @Html.Partial("FizzBuzzList")

            }
     </div>
</div>
}

FizzBuzz/FizzBuzz/Views/Shared/FizzBuzzList.cshtml
@model FizzBuzz.Models.FizzBuzzModel
@using PagedList.Mvc;
<div class="divResult">
    @if (Model != null)
    {
        foreach (var item in Model.Result)
        {
            var result = item.Split(' ');
            foreach(var str in result)
            {
            <span class="@str">@str</span>
        
             }
             <br />
        }
    }

    <div id="container" style="margin-left: 20px">

    @{
        var renderOptions = PagedListRenderOptions.Minimal;
        renderOptions.LinkToPreviousPageFormat = "Previous";
        renderOptions.LinkToNextPageFormat = "Next";
    }

    <div class="pagination" style="margin-left: 400px">
        @Html.PagedListPager(Model.Result, page => Url.Action("Home", new { Model.UserInput, page }), renderOptions)
    </div>
</div>

FizzBuzz/FizzBuzz/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
     @Styles.Render("~/Content/css")
     @Scripts.Render("~/bundles/jquery")
     @Scripts.Render("~/bundles/jqueryui")
     @Scripts.Render("~/bundles/jqueryval")
</head>
<body>
<div class="container body-content">
        @RenderBody()
</div>
</body>
</html>
  